version: "3.8"

services:
  chat-app:
    image: chat_app_image:latest
    build:
      context: .
    ports:
      - "8115:8115"
    networks:
      - chat-app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-app

  mongo:
    image: mongo:5.0.7
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - chat-app-network
    volumes:
      - mongo-data:/data/db

networks:
  chat-app-network:
    driver: bridge

volumes:
  mongo-data:
