services:
  chat-app:
    image: chat_app_image:latest
    build:
      context: .
    ports:
      - "8115:8115"
    networks:
      - chat-app-network

  mongo:
    image: mongo:5.0.7
    restart: always
    ports:
      - "27017:27017"
    networks:
      - chat-app-network
    volumes:
      - mongo-data:/data/db

networks:
  chat-app-network:
    driver: bridge
